name: Build and Deploy Bottle App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set this in your repo secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Set this in your repo secrets

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: avnlearn/avnlearn-server:latest  # Replace with your Docker Hub username and image name

    - name: Deploy to your server (optional)
      run: |
        # Add your deployment commands here, e.g., SSH into your server and run Docker commands
        echo "Deployment step goes here"
